### ISSUE TITLE
Support for local symbols for functions/variables/etc.

### ISSUE THREAD

**Issue by sunfishcode** [m4b/faerie#16]
Faerie's current API doesn't seem to have a way to give functions or variables "local" binding, which is STB_LOCAL in ELF. For example, in the top-level README.md, "str.1" is emitted as an externally-visible symbol, so it'll collide with "str.1" symbols defined in other modules.

(There are also a bunch of other related things we'll eventually want, such as symbol visibilities, weak symbols, symbol aliases, and other goodies, but I'm only mentioning this in case it influences the API design direction.)

**Comment by m4b** [comment]
Yea that shouldn’t be hard. So latest commit added the ImportKind to imports.

However in reflection I believe we need a pass where all the different symbols are “declared”; here we’d add whether it’s an import or a symbol (local or otherwise). Here I think we’d also declare whether it’s read only, writeable, etc, for data objects (which we also don’t have). 

This gets rid of a weirdness with using link_import on a local function (but which hadn’t been declared an import), and defaulting to PLT reloc when not found. (More accurately, this is a hack)

This way we’d only have _a single link function_, and it takes care of depositing it into the correct container depending on the kind of symbol it is asked to link (or not at all and we just pass this glob of info to the respective backend and they can do whatever they want with it)

As I noted this will cause the artifact method calls to have strict order of operations at runtime but as long as we document this (and error properly when a symbol is mentioned in a link but hasn’t been declared), I think it’s the best path forward for adding “symbol features” in a platform agnostic way. 

Is this something that seems reasonable ?

**Comment by sunfishcode** [comment]
My current experiments all already have a separate pass that declares everything before doing the definitions, so this would be easy to adopt.

I do have one concern: could the scheme be relaxed to allow importing functions on the fly? If I've declared all the defined symbols up front, and then later on in the middle of defining the functions to faerie I suddenly notice that I need to add "__muldi3" or something to the imports list because codegen generated a call to it at the last moment, can that be accommodated?

**Comment by m4b** [comment]
Yes I think that would be fine as long as you don’t ever reference that import before. (But how could you, since you just noticed it)

Otherwise if you add it after it just would have to be declared and then you can add relocations against it as normal. In other words, creating the initial list of symbols doesn’t “seal” it in some sense, like a builder might. 

The backing implementation I’m thinking is just a hashmap from symbol name to type and properties.

So adding one after fact shouldn’t change anything (only referencing it will cause symbol not found error, etc)

**Comment by sunfishcode** [comment]
Sounds good.

**Comment by m4b** [comment]
closed in 3d33b1d
