### ISSUE TITLE
Linking ELF can cause a panic

### ISSUE THREAD

**Issue by pchickey** [m4b/faerie#30]
When a declared `Function` has a link pointing to it, but has not been defined, the Elf::link function will panic.

Reproduced at https://github.com/pchickey/faerie/tree/pch/reproduce_link_panic

I elaborated the panic with an error message in #29 .

**Comment by m4b** [comment]
Sorry just got to this.

@pchickey 

So examining this, I believe that this is a fundamental logic error on the user part, no? (the bug is this should be an error instead of a panic)

E.g., the user is declaring a function without defining it, and then claiming there is a relocation somewhere in an undefined body of the function (already we make no sense here) to another object.

We need to return an error like above somewhere in the pipeline, if I'm not mistaken?

Or am I missing something?

**Comment by m4b** [comment]
Hah, derp, its the other way around, iiuc, i was looking at order here instead of struct names ;P

```rust
    let code = vec![1, 2, 3, 4];
    obj.define("b", code).expect("can define b");
    obj.link(Link {
        to: "a",
        from: "b",
        at: 0,
    }).expect("can link a to b");
```

(and my expect message is wrong)

So the problem is that b is defined, has a relocation at 0 offset, to a declared (but not defined) A; i can't remember but this sounds similar to the earlier promotion logic for imports and globals, so this might be a faerie bug instead of user, i think?

**Comment by m4b** [comment]
So afaics, there are a couple of things to do in this case:

1. Promote undef'd global declarations to function imports at emit time
2. Error at link time for undef'd global declarations

I would prefer 2.; 1. is more C-like I suppose, but its adding even more auto-promotion, and essentially make the strongly typed declarations in faerie now semi-pointless imho, but I am open to being persuaded otherwise if there are good motivating reasons for 1.

Anyone feel free to chime in here.

**Comment by pchickey** [comment]
Agree its a user error, I only hit it because I made a bug in my own code.

`Result<_, Error>` at `emit` time is the right way to handle it, I think. Making a non-import declaration is a contract for the user to define it sometime before `emit`. If they don't keep up their end of the contract, send them an error saying so.

Automatically promoting a non-import declaration to import would paper over the bug and, I suspect, make it much harder to discover.

**Comment by pchickey** [comment]
I can do this fix as well, unless you want to take it

**Comment by m4b** [comment]
Sure if you have a fix go for it!
