### ISSUE TITLE
Malformed elf when artifact name matches def name

### ISSUE THREAD

**Issue by pchickey** [m4b/faerie#31]
We found a bug where an elf created with the same artifact name as a definition name (see example below) will cause gnu `ld` and other binutils to reject the created file with ` file not recognized: File truncated`.

```
    let mut obj = Artifact::new(Target::X86_64, "a".into());
    obj.declare("a", Decl::Function { global: true }).unwrap();
    obj.define("a", vec![1, 2, 3, 4]).unwrap();
```

I think this has to do with the way strings are interned, but I don't yet understand the ELF format enough to attempt to fix it myself.

Made a failing test that shells out to `ld` in https://github.com/pchickey/faerie/tree/pch/reproduce_link_panic

**Comment by m4b** [comment]
Hmmm the artifact name being Interned shouldn’t affect it, but it might be interacting witg some of the redef logic, have to check.

**Comment by m4b** [comment]
@pchickey 

Heh; this is also an issue in C:

```bash
m4b@derp ::  [ /tmp ] cat a
extern int a ();
m4b@derp ::  [ /tmp ] cc -c -o a.o a
cc: warning: a: linker input file unused because linking not done
m4b@derp ::  [ /tmp ] file a.o
a.o: cannot open `a.o' (No such file or directory)
```

**Comment by sunfishcode** [comment]
@m4b That's `cc` not recognizing `a` as a source file, by inspecting its (lack of) filename extension. (And then oddly issuing a warning rather than a fatal error.)

I wonder if the problem above is somehow a collision between the STT_FILE symbol for the artifact and the STT_FUNC symbol for the function.

**Comment by m4b** [comment]
@sunfishcode Ah yea, totally right, changing to b is same issue. Warning is def weird, probably should file a bug upstream.

I'm debugging now, but I've narrowed it down to an issue in the emitted section headers, something is wrong there.

**Comment by m4b** [comment]
Heh; this is an extremely unpleasant bug.

```diff
diff --git a/src/elf.rs b/src/elf.rs
index f4278f9..e9a719e 100644
--- a/src/elf.rs
+++ b/src/elf.rs
@@ -379,11 +379,19 @@ impl<'a> Elf<'a> {
         }
     }
     fn new_string(&mut self, name: String) -> (StringIndex, usize) {
+        let nstrings = self.strings.len();
         let size = name.len() + 1;
-        let offset = self.sizeof_strtab;
-        let idx = self.strings.get_or_intern(name);
-        self.offsets.insert(idx, offset);
-        self.sizeof_strtab += size;
+        let idx = self.strings.get_or_intern(name.as_str());
+        // https://github.com/m4b/faerie/issues/31 - name same as a symbol
+        let offset = if nstrings < self.strings.len() {
+            // new string
+            let offset = self.sizeof_strtab;
+            self.offsets.insert(idx, offset);
+            self.sizeof_strtab += size;
+            offset
+        } else {
+            *self.offsets.get(&idx).expect(&format!("{} was not a unique string, but it is not in the string offset hashmap", name))
+        };
         (idx, offset)
     }
     pub fn add_definition(&mut self, name: &str, data: &'a [u8], prop: &artifact::Prop) {
```

So this patch does not completely fix the issue, because https://github.com/m4b/faerie/blob/651224beb938a0e14c0e484f97156f2f32658ed5/src/elf.rs#L421

uses the string interned index to insert into the order map, which then overwrites the value for the the `SHN_FILE` entry in the symbol table.

I suppose can add a hack where the SHN file name is added at the write step but I don't want to because:

1. it will cause more magic offset values to be added in the various table offset computations, and other stuff, which is already way too brittle.
2. It will only allow one file name per object file, which is how it is now, but it would preclude future features to allow this possibility.

I think the best solution without introducing any (more) technical debt is to fix the elf internal writer to be more like the mach-o version, but I don't think I have time for this :/

**Comment by pchickey** [comment]
I can take some time to fix it. On Monday I will take a look at the mach-o version of the code and see if I can figure out how to fix the internal writer. If I need more guidance I'll ping you.
