### ISSUE TITLE
Weak linkage support

### ISSUE THREAD

**Issue by bjorn3** [m4b/faerie#60]
This is needed for libstd:

https://github.com/rust-lang/rust/blob/1a51bb8174e97251a37fcd83ff8750b7773e762a/src/libstd/sys/unix/fast_thread_local.rs#L22

**Comment by bjorn3** [comment]
cc bjorn3/rustc_codegen_cranelift#146

**Comment by pchickey** [comment]
My plan is to change the `global :bool` field in the relevant `artifact::Decl` variants to instead be `scope: Scope` where `pub enum Scope { Local, Global, Weak }`. I don't want to re-use the ELF term "binding" for this in the public API because its confusing, and there is already a concept of `artifact::Binding` in the library.

Based on my reading of goblin's mach code, it appears there is a flag to mark exports as weak definitions, so this scheme should be supportable with mach (https://github.com/m4b/goblin/blob/master/src/mach/exports.rs#L25). I'd love if someone could point me to reference materials on the mach file format. Unfortunately, I don't have access to a machine running Mac OS to test this, but I could probably convince my employer to send me a retired macbook.
